  //temporary data
  export const userRows = [
    {
      id: 1,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 2,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 3,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 4,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 5,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 6,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 7,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 8,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 9,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 10,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: 100,
    },
    {
      id: 11,
      nickname: "Snowww",
      firstname: "John",
      lastname: "Snow",
      email: "1snow@gmail.com",
      usertype: "Affiliate",
      balance: -100,
    },
  ];